### PR TITLE
Fix job settings inputs

### LINKED ISSUE #467: TypeError: n.inputNode.blur is not a function
https://sentry.io/cph/client/issues/493405814/

```
TypeError: n.inputNode.blur is not a function
  at t.value [as blur] (/static/app.a9b5a604.js:1:1171181)
  at t.<anonymous> (/static/app.a9b5a604.js:1:1170983)
  at e.notifyAll (/static/app.a9b5a604.js:1:439325)
  at a.close (/static/app.a9b5a604.js:1:148786)
  at a.closeAll (/static/app.a9b5a604.js:1:248956)
...
(9 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by Miminko**
- resolves #467

### CODE REVIEW

File: client/src/js/settings/components/Jobs/TaskField.js [hunk 1]
```diff
@@ -9,19 +9,21 @@ export default class TaskField extends React.PureComponent {
     constructor (props) {
         super(props);
         this.state = {
+            name: this.props.name,
```
Comment (igboyes) [inline client/src/js/settings/components/Jobs/TaskField.js]: Not necessary to add `name` to `state`. Putting `props` in `state` is almost always an anti-pattern.

File: client/src/js/settings/components/Jobs/TaskField.js [hunk 2]
```diff
@@ -44,7 +46,7 @@ export default class TaskField extends React.PureComponent {
     handleSubmit = (e) => {
         e.preventDefault();
         this.setState({pending: true}, () => {
-            this.props.onChange(this.state.value);
+            this.props.onChange(this.state.name, this.state.value);
```
Comment (igboyes) [inline client/src/js/settings/components/Jobs/TaskField.js]: Use `this.props.name` after fixing the first change (`name` should stay in `prop`).
