### PR TITLE
Graceful API error handlers

### LINKED ISSUE #436: Gracefully handle all expected API errors in client
Perform validation on client prior to sending request wherever possible.

If there is a chance that server validation may fail even if client validation passed, make sure that validation error from server is handled. Example is email validation.

Some if these are already implemented. In that case, check the box.

#### Account
- [ ] `422` PATCH /api/account
Email values may fail server validation even if they pass client validation

- [ ] `400` PUT /api/account/password
Old password is incorrect

- [ ] `422` PUT /api/account/password
Password or old password are invalid (length) or missing

#### Samples
- [ ] `422` POST /api/samples
Sample name is already in use

- [ ] `422` PATCH /api/samples/:sample_id
Sample name is already in use

#### Viruses
- [ ] `409` POST /api/viruses
Name or abbreviation in use

- [ ] `409` PATCH /api/viruses
Name or abbreviation in use

- [ ] `422` PATCH /api/viruses
Duplicate segment names in schema

- [ ] `404` POST /api/viruses/:virus_id/isolates/:isolate_id/sequences
Segment name does not exist in virus schema

- [ ] `409` POST /api/viruses/:virus_id/isolates/:isolate_id/sequences
Sequence ID already exists

- [ ] `422` POST /api/viruses/:virus_id/isolates/:isolate_id/sequences
ID (AKA accession), definition, or sequence fields fail length == 1

- [ ] `404` PATCH /api/viruses/:virus_id/isolates/:isolate_id/sequences
Segment name does not exist in virus schema

- [ ] `422` POST /api/viruses/:virus_id/isolates/:isolate_id/sequences
Definition, or sequence fields fail length == 1

#### Indexes
- [ ] `400` POST /api/indexes
There are unverified viruses

#### Subtraction
- [ ] `409` POST /api/subtraction
Subtraction id (name) is already in use

- [ ] `422` POST /api/subtraction
Subtraction id or file_id are missing

#### Users

- [ ] `409` POST /api/users
User id is already in use

- [ ] `422` POST /api/users
Password or username are too short or missing

- [ ] `422` PATCH /api/users
Password is too short or missing

#### Groups
- [ ] `409` POST /api/groups
Group id already exists

- [ ] `422` POST /api/groups
Group id missing

### PR DESCRIPTION
**Pull request by Miminko**
- resolves #436

### CODE REVIEW

File: client/src/js/errors/reducer.js [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+};
+
+export default function errorsReducer (state = null, action) {
+
+    const failedAction = checkActionFailed(action);
+    let errorName;
+
+    if (failedAction) {
+        errorName = getErrorName(action);
+    } else if (action.type === CLEAR_ERROR) {
```
Comment (igboyes) [inline client/src/js/errors/reducer.js]: The `if (action.type === CLEAR_ERROR)` conditional should be moved to the top of the reducer.

This is a quick check that will let you avoid calling `checkActionFailed()` unnecessarily.

File: client/src/js/samples/components/Create/Create.js [hunk 2]
```diff
@@ -66,51 +75,62 @@ class CreateSample extends React.Component {
...
+            }
+        } else {
+            this.setState({
+                [name]: e.target.value
+            });
+        }
+
     };
 
     handleSubmit = (e) => {
```
Comment (igboyes) [inline client/src/js/samples/components/Create/Create.js]: Same thing as earlier. Avoid reusing variables for different values. Instead use `hasError` and directly assign error messages to `state` properties.

File: client/src/js/subtraction/components/Create.js [hunk 3]
```diff
@@ -50,48 +51,64 @@ class CreateSubtraction extends React.Component {
...
+            fileId: fileId === this.state.fileId ? "" : fileId,
+            errorFile: ""
         });
     };
 
     handleSubmit = (e) => {
         e.preventDefault();
 
-        const errors = [];
+        let error = "";
```
Comment (igboyes) [inline client/src/js/subtraction/components/Create.js]: Use `hasError` and direct assignment of state properties.

File: client/src/js/users/components/Create.js [hunk 4]
```diff
@@ -40,45 +65,32 @@ export class CreateUser extends React.PureComponent {
     handleSubmit = (e) => {
         e.preventDefault();
 
-        const errors = [];
+        let error = "";
```
Comment (igboyes) [inline client/src/js/users/components/Create.js]: `hasError`
